site_name: RhinoInsideCadwork
repo_url: https://github.com/Brunner246/RhinoInsideCadwork

# Copyright
copyright: Copyright &copy; 2021 cadwork 

theme:
    name: material
    palette:
      - scheme: default
        primary: green
        accent: indigo

nav:
    - General: index.md
    - Documentation:
      - 01 Attributes / Selection: 01.md
      - 02 Elements: 02.md
      - 03 Architectural: 03.md

markdown_extensions:
  - attr_list  