site_name: RhinoInsideCadwork
repo_url: https://github.com/Brunner246/RhinoInsideCadwork

# Copyright
copyright: Copyright &copy; 2021 cadwork 

theme:
    name: material
    logo: cw_logo.svg
    palette:
      - scheme: default
        primary: green
        accent: indigo


markdown_extensions:
  - attr_list  

extra:
  generator: false
  copyright: Copyright & copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brunner246
      name: RhinoInsideCadwork
  alternate:
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr
    - name: English
      link: ./en/
      lang: en

plugins:
  - search:
      separator: '[\s\-\.\_]+'  
  # - mkdocs-versioning:
      # version: version 28.0
  - i18n:
      default_language: de
      #default_language: !ENV [DEFAULT_LANGUAGE, "de"]
      #default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        de: Deutsch
        fr: Français   
        en: English 
      nav_translations:
        fr:
          Attribute: Attribute
          Elemente: Elements
          Architektur: Architecture
        en:
          Attribute: Attribute
          Elemente: Elements
          Architektur: Architecture
