site_name: RhinoInsideCadwork

theme:
   name: material
   palette:
    - scheme: default
      primary: green
      accent: indigo

nav:
    - General: index.md
    - Documentation:
      - 01 Attributes / Selection: 01.md
      - 02 Elements: 02.md
      - 03 Architectural: 03.md

markdown_extensions:
  - attr_list  